# Generated by Django 5.1.5 on 2025-01-16 14:56

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=30, null=True)),
                ('start_at', models.DateField(default=django.utils.timezone.now)),
                ('end_at', models.DateField(blank=True, null=True)),
                ('describe', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Project Info',
                'verbose_name_plural': 'Project Infos',
            },
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=15, unique=True)),
                ('badge_file', models.FileField(blank=True, null=True, upload_to='badge/')),
            ],
            options={
                'verbose_name': 'Skill Set',
                'verbose_name_plural': 'Skill Sets',
            },
        ),
        migrations.CreateModel(
            name='ContentMetadata',
            fields=[
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='content_metadata', serialize=False, to='api.projectinfo')),
                ('content', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Content Metadata',
                'verbose_name_plural': 'Content Metadata',
            },
        ),
        migrations.CreateModel(
            name='ReadMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(blank=True, null=True, upload_to=api.models.get_file_upload_path)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readme', to='api.projectinfo')),
            ],
        ),
        migrations.CreateModel(
            name='FiledInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed', models.CharField(blank=True, max_length=30, null=True)),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skillset')),
            ],
            options={
                'verbose_name': 'Filed Info',
                'verbose_name_plural': 'Filed Infos',
            },
        ),
        migrations.CreateModel(
            name='SkillMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_mappings', to='api.projectinfo')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_mappings', to='api.skillset')),
            ],
            options={
                'verbose_name': 'Skill Mapping',
                'verbose_name_plural': 'Skill Mappings',
                'unique_together': {('project_id', 'skill_id')},
            },
        ),
    ]
