# Generated by Django 5.1.1 on 2024-11-19 13:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=30, null=True)),
                ('start_at', models.DateField(default=django.utils.timezone.now)),
                ('end_at', models.DateField(blank=True, null=True)),
                ('describe', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('readme_file', models.FileField(blank=True, null=True, upload_to='readme/')),
            ],
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('skill_name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('badge_file', models.ImageField(blank=True, null=True, upload_to='badge/')),
            ],
        ),
        migrations.CreateModel(
            name='ContentMetadata',
            fields=[
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='content_metadata', serialize=False, to='api.projectinfo')),
                ('content', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_mappings', to='api.projectinfo')),
                ('skill_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_mappings', to='api.skillset')),
            ],
            options={
                'verbose_name': 'Skill Mapping',
                'verbose_name_plural': 'Skill Mappings',
                'unique_together': {('project_id', 'skill_name')},
            },
        ),
    ]
