# Generated by Django 5.1.1 on 2024-11-22 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentmetadata',
            options={'verbose_name': 'Content Metadata', 'verbose_name_plural': 'Content Metadata'},
        ),
        migrations.AlterModelOptions(
            name='projectinfo',
            options={'verbose_name': 'Project Info', 'verbose_name_plural': 'Project Infos'},
        ),
        migrations.AlterModelOptions(
            name='skillset',
            options={'verbose_name': 'Skill Set', 'verbose_name_plural': 'Skill Sets'},
        ),
    ]
