# Generated by Django 5.1.1 on 2025-01-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'User Set',
                'verbose_name_plural': 'User Sets',
            },
        ),
    ]
