# Generated by Django 5.1.1 on 2024-11-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_contentmetadata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillset',
            name='badge_file',
            field=models.FileField(blank=True, null=True, upload_to='badge/'),
        ),
    ]
