version: '3.8'

services:
  nginx:
    image: who-am-i-nginx # Nginx 이미지
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"

  nginx_exporter:
    image: who-am-i-nginx_exporter
    restart: unless-stopped

    depends_on:
      - nginx

  postgresql:
    image: who-am-i-postgresql # PostgreSQL 이미지
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data # PostgreSQL 데이터 저장용 볼륨

  python:
    image: who-am-i-python # Python 앱 이미지

    restart: unless-stopped
    depends_on:
      - postgresql

    deploy:

      replicas: 3

  redis:
    image: who-am-i-redis # Redis 이미지
    restart: unless-stopped

  prometheus:
    image: who-am-i-prometheus # Prometheus 이미지
    restart: unless-stopped

  grafana:
    image: who-am-i-grafana # Grafana 이미지
    restart: unless-stopped
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/grafana # Grafana 데이터 저장용 볼륨

  locust:
    image: who-am-i-locust
    restart: unless-stopped
    depends_on:
      - python
    volumes:
      - locust-data:/app # Locust 데이터 저장용 볼륨

volumes:
  nginx-data: # Nginx 볼륨 정의
  postgres-data: # PostgreSQL 볼륨 정의
  redis-data: # Redis 볼륨 정의
  prometheus-data: # Prometheus 볼륨 정의
  grafana-data: # Grafana 볼륨 정의
  locust-data:
    # Locust 볼륨 정의


