version: '3.8'

services:
  nginx:
    image: who-am-i-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"

  postgresql:
    image: who-am-i-postgresql
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    ports:
      - "5432:5432"

  python:
    image: who-am-i-python
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgresql

  redis:
    image: who-am-i-redis
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"

  prometheus:
    image: who-am-i-prometheus
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"

  grafana:
    image: who-am-i-grafana
    build:
      context: ./grafana
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  locust:
    image: who-am-i-locust
    build:
      context: ./locust
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
