version: '3.8'

services:
  nginx:
    image: who-am-i-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80" # HTTP 포트
      - "443:443" # HTTPS 포트
    depends_on:
      - python

  nginx_exporter:
    image: who-am-i-nginx_exporter
    build:
      context: ./nginx-exporter
      dockerfile: Dockerfile
    depends_on:
      - nginx

  postgresql:
    image: who-am-i-postgresql
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    # PostgreSQL 포트 매핑 제거

  python:
    image: who-am-i-python
    build:
      context: ./python
      dockerfile: Dockerfile
    # Python 포트 매핑 제거
    depends_on:
      - postgresql

  redis:
    image: who-am-i-redis
    build:
      context: ./redis
      dockerfile: Dockerfile
    # Redis 포트 매핑 제거

  prometheus:
    image: who-am-i-prometheus
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    # Prometheus 포트 매핑 제거

  grafana:
    image: who-am-i-grafana
    build:
      context: ./grafana
      dockerfile: Dockerfile
    # Grafana 포트 매핑 제거
    depends_on:
      - prometheus

  locust:
    image: who-am-i-locust
    build:
      context: ./locust
      dockerfile: Dockerfile
    # Locust 포트 매핑 제거

networks:
  default:
    driver: bridge
