global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'python'
    static_configs:
      - targets: ['python:8000']  # DNS를 통해 접근 가능

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter:9113'] # Exporter의 주소

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000'] # grafana의 서비스 이름과 포트

